# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h localhost
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
  server:
    restart: on-failure
    image: python-api-2
    volumes:
      - ./server:/server
    build:
      context: ./server
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000

