version: '3.1'
services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  server:
    image: python-api
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PORT
      - MYSQL_HOST=db
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
