# .github/workflows/deploy-microservices.yml
name: Deploy Microservices to Scalingo

on:
  push:
    branches:
      - main # Déclencheur sur les push vers la branche main

jobs:
  # Job pour provisionner/mettre à jour l'infrastructure Scalingo avec Terraform
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="scalingo_api_token=${{ secrets.SCALINGO_API_TOKEN }}"
        env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }} # Assurez-vous que c'est un secret GitHub

  # Job pour construire et déployer l'API Web
  deploy_web:
    runs-on: ubuntu-latest
    needs: terraform_apply # Dépend que l'infra Terraform soit à jour
    steps:
      - name: Checkout code (your web-api service code)
        uses: actions/checkout@v3
        # Si votre code est dans un sous-dossier, spécifiez path: ./services/web-api

      - name: Login to Scalingo CLI
        run: echo "${{ secrets.SCALINGO_API_TOKEN }}" | scalingo login --api-token-stdin

      - name: Deploy Web API to Scalingo
        run: scalingo deploy --app my-microservices-app-tf --type web-api --docker-image your-dockerhub-user/web-api